image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker login registry.gitlab.com -u $reg_user -p $reg_token

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/$reg_org/main-app/mainapp:latest .
    - docker push registry.gitlab.com/$reg_org/main-app/mainapp:latest